### ISSUE TITLE
Muxumux - Error 500

### ISSUE THREAD

**Issue by element465** [tom472/mediabox#59] opened 2018-08-21 10:08 UTC
Another error, this one doesn't look like to be related to me!

Muximux was working fine, then all of a sudden I get an error 500: http://prntscr.com/kl5lns

It has been working fine for the last 24 hours, and then without touching anything, it just plays up like this.

It seems it may be an issue with Muximux as other people seem to get the issue randomly. I've also had it do it on another docker install before.

Have you experienced it before?

**Comment by tom472** [comment] 2018-08-21 13:14
Hmm - I've never once had that happen - been running this set-up for about half a year now since Muximux was added in.

Can you use Portainer to check the logs for Muximux and see if there is anything logged?

Also can you make sure you have cleared any cache from your browser for your Mediabox site.

Or possibly test/try an incognito session when the issue is happening so that it can be tested while a fresh / no history / no cache browser session?

**Comment by ageisen2000** [comment] 2018-08-22 13:36
I've also had this error occur. It ended up being an issue with the container itself I think. After completely removing the container and re-downloading it the issue was fixed. I don't think it's an issue of mediabox

**Comment by tom472** [comment] 2018-08-22 14:25
@ageisen2000 Thanks for the info - Guess it's just that I haven't seen it.

I would suppose that maybe when Mediabox is starting up for the first time and grabbing so many containers it's possible one might get a little funky.

@element465 Can you use Portainer to stop the Muximux container, delete its image and then go back to your Mediabox directory and run `docker-compose up -d` this will re-pull Muximux and get it fired up.

Let me know.

Thanks
--Tom

**Comment by tom472** [comment] 2018-08-27 21:05
Guess we'll call this Closed in that it appears to be a transient issue with Muximux sometimes.

**Closed by tom472** 2018-08-27 21:05 UTC
