### ISSUE TITLE
Sonarr and Deluge import issue

### ISSUE THREAD

**Issue by cthog** [tom472/mediabox#53] opened 2018-07-11 10:54 UTC
For some reason, my sonarr can't see the file downloaded by deluge for import.  Typically, I've solved this issue by adding a remote path map to the appropriate directory.  Deluge is downloading to /data/incomplete and then moving to /data/completed.  Sonarr doesn't see that directory--presumably it wants to pull from /downloads.  I tried mapping the two, but that doesn't seem to work.  

Before jumping into Portainer and adding volumes, changing destinations, I figured I'd ask, as I don't want to mess up the overall setup. 

Fine job, by the way, thank you for your efforts.

--Chris

**Comment by tom472** [comment] 2018-07-11 14:33
Thanks for the compliment!

So `/downloads` in the Sonarr container **is** Deluge's `/data/completed`

So you should only need to point Sonarr at (its) `/downloads` as the completed files location.

Here are the relevant parts from the Docker Compose File:

For Deluge:
Deluge maps its internal `/data` to Mediabox's `/content`
And uses `/data/incomplete` and `/data/completed` as the in-progress and complete locations.

`volumes:`
    `- './content:/data'`
    `- './delugevpn/config:/config'`


For Sonarr:
Sonarr maps its internal `/downloads` to Mediabox's `/content/completed`

`volumes:`
    `- './sonarr:/config'`
    `- './content/completed:/downloads'`
    `- '${TVDIR}:/tv'` 

Does that help / make sense?

**Comment by cthog** [comment] 2018-07-11 15:24
Thank you, I got that, and that is indeed what each container has mapped.  However, I've got a downloaded torrent sitting in /data/completed (so /content/completed and /downloads, respectively), but Sonarr is telling me that it can't find any video files to import.  I actually had pretty much the same setup before utilizing your excellent tool (until I saw mediabox, I had put off a new install, and had actually been working off a cloned image of an earlier ubuntu hardware setup, so thank goodness for you.)  

In my prior setup, I had DelugeVPN and Sonarr in separate docker images (but I didn't have them in stacks, so I was losing jackett connectivity in docker.)  As I mentioned in my first post, in order to resolve a similar issue with downloads not being processed, I had to use Sonarr's mapping feature in the Download Client section, which resolved the problem.  I gave that a halfhearted whirl this morning as I was on my way out the door, but that didn't seem to help.

In your test setup, are your sonarr torrents getting into the tv folder?

**Comment by tom472** [comment] 2018-07-11 15:54
I'll have to give it a test again - 
I don't use Sonarr so I'll have to turn it back on and run a test.

**Comment by cthog** [comment] 2018-07-11 19:07
I appreciate you taking a look.  I'll fiddle with it some more tonight, if need be.

**Comment by cthog** [comment] 2018-07-11 21:36
Fixed it.  I found this post instructive: https://www.reddit.com/r/sonarr/comments/87jimv/sonarr_deluge_docker_setup_not_downloading/?st=jjhmz3tk&sh=3de6a8f7

Apparently someone already had this issue.  I went into Portainer and changed the local folder from /downloads to /data/completed and it instantly imported my pending files.

I'm pretty sure this will be required for Radarr, but will test nzbget without making the change and report back.

**Comment by cthog** [comment] 2018-07-11 22:18
Had to change nzbget volume mount as follows:

/home/admin/mediabox/content/completed | /data/completed

nzbget/deluge working with Sonarr.  Have similar settings with Radarr, testing now.

**Comment by tom472** [comment] 2018-07-12 00:45
Awesome - thanks for working on figuring it out, and coming back to post it.

So to verify what fixed it for you ...

In Portainer - you switched **container** volume: `/downloads` to `/data/completed`
For the section that paired with **host** volume: `/home/tom/mediabox/content/completed`

Is that correct?

And the nbzget volume mount change - was that for the nbzget conatiner, or the nbzget settings in Sonarr?

**Comment by tom472** [comment] 2018-07-12 01:52
Just did some testing and you nailed it @cthog thanks so much for pointing it out.

Also do you have any issues with the (Sonarr) torrents removing themselves from Deluge when complete? On the Download Client tab under the section "Completed Download Handling" can you let me know what settings you have for the two toggle options: Enable & Remove

Also - do you want to create a PR for the volume mapping fixes to get the credit for them?
Because I'll want to get them fixed and merged in quickly - hopefully by like tomorrow night.

Let me know.

Thanks again for catching this and letting me know about it.

**Comment by WoosterInitiative** [comment] 2018-07-12 16:09
I'm speaking a bit out of turn and a little above my head, but I wonder if the issue is caused by the fact that Sonarr/Radarr look to Deluge to tell them where the files are? Because the paths are different, I would assume that they look where Deluge tells them, but that's not where that container is looking.

Mostly so that I can understand the "why", does this jibe with what you guys are understanding here?

**Comment by tom472** [comment] 2018-07-12 16:39
@WoosterInitiative Yes - that is pretty much the case.
Even tho Mediabox is mapping `/data/completed` to `/downloads` in Sonarr
Sonarr is asking Deluge's API - Where is the file?
Deluge is saying `/data/completed` << In reference to **Deluge's** container.
But **Sonarr** says Oh OK - I'll look in `/data/completed` << In **my** container - and that is not where the mapping is.

This can be fixed with a setting available in Sonarr - remote path mapping - 
Or
Even better - I'll just adjust the mappings in the Mediabox compose file to adjust for this setting and it should be all good.

**Comment by tom472** [comment] 2018-07-13 02:30
OK this should be fixed now for Sonarr and Radarr - 

I'll leave this thread open for a bit longer in case there is any more feedback.

To get the new fixed version just go into your Mediabox directory and re-run the `./mediabox.sh` script.

Thanks 
--Tom

**Comment by tom472** [comment] 2018-07-13 14:01
@cthog Thanks for the comments - and for finding this issue.

No worries on going AWOL - I know how that goes.

Things look pretty good for now - and I do have some ideas on cleaning up the folder structure a bit overall.

Thanks again. 

I'll probably close this tonight.

**Closed** 2018-07-15 14:17 UTC
